# app.yaml

env: standard
runtime: nodejs16
service: default

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html